version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Moving to the project directory
          command: cd src/Project/
      - run:
          name: Building the project
          command: dotnet publish -c Release -o out
      - run:
          name: Run result
          command: dotnet out/Project

